apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins-extend
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: jenkins-extend
      template: jenkins-master-s2i
    name: jenkins-extend
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-extend:latest
    postCommit: {}
    resources:
      limits:
        memory: 1Gi
    runPolicy: Serial
    source:
      contextDir: master
      git:
        ref: master
        uri: https://github.com/jarielpa/jenkins-s2i-example.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins-base:latest
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: jenkins-extend
    name: jenkins-extend
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: jenkins-extend:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
